export type SeoLandingConfig = {
  slug: string
  title: string
  seoTitle: string
  seoDescription: string
  h1: string
  seoText: string
  categorySlug: string
  internalCategorySlug: string
  city?: string
  fixedParams?: Record<string, string>
  indexable: boolean
  priority: number
  changefreq: "daily" | "weekly" | "monthly"
}

/** Программные SEO-лендинги (/s/...).
 *  Покрывают комбинации город × категория для органического трафика.
 *  Страницы невидимы в интерфейсе — только для поисковиков.
 */
export const SEO_LANDING_PAGES: SeoLandingConfig[] = [
  // ─── УСЛУГИ × ГОРОДА ─────────────────────────────────────────────────────
  {
    slug: "remont-holodilnikov-krasnodar",
    title: "Ремонт холодильников в Краснодаре",
    seoTitle: "Ремонт холодильников в Краснодаре — мастера | Нашло",
    seoDescription: "Найдите мастера по ремонту холодильников в Краснодаре. Актуальные объявления услуг с отзывами и контактами.",
    h1: "Ремонт холодильников в Краснодаре",
    seoText: "Подборка объявлений по ремонту холодильников в Краснодаре на Нашло. Сравнивайте цены, сроки и опыт мастеров.",
    categorySlug: "services",
    internalCategorySlug: "services",
    city: "Краснодар",
    fixedParams: { subcategory: "repair_home" },
    indexable: true,
    priority: 0.75,
    changefreq: "weekly",
  },
  {
    slug: "remont-holodilnikov-moskva",
    title: "Ремонт холодильников в Москве",
    seoTitle: "Ремонт холодильников в Москве — выезд на дом | Нашло",
    seoDescription: "Мастера по ремонту холодильников в Москве. Быстрый выезд, честные цены, гарантия.",
    h1: "Ремонт холодильников в Москве",
    seoText: "На Нашло собраны объявления мастеров по ремонту холодильников в Москве. Сравнивайте цены и отзывы.",
    categorySlug: "services",
    internalCategorySlug: "services",
    city: "Москва",
    fixedParams: { subcategory: "repair_home" },
    indexable: true,
    priority: 0.8,
    changefreq: "weekly",
  },
  {
    slug: "remont-stiralnyh-mashin-spb",
    title: "Ремонт стиральных машин в Санкт-Петербурге",
    seoTitle: "Ремонт стиральных машин в Санкт-Петербурге | Нашло",
    seoDescription: "Найдите мастера по ремонту стиральных машин в Санкт-Петербурге. Объявления с ценами и отзывами.",
    h1: "Ремонт стиральных машин в Санкт-Петербурге",
    seoText: "Объявления по ремонту стиральных машин в Санкт-Петербурге. Выезд на дом, гарантия на работы.",
    categorySlug: "services",
    internalCategorySlug: "services",
    city: "Санкт-Петербург",
    fixedParams: { subcategory: "repair_home" },
    indexable: true,
    priority: 0.75,
    changefreq: "weekly",
  },
  {
    slug: "remont-stiralnyh-mashin-moskva",
    title: "Ремонт стиральных машин в Москве",
    seoTitle: "Ремонт стиральных машин в Москве — выезд на дом | Нашло",
    seoDescription: "Мастера по ремонту стиральных машин в Москве. Быстро, качественно, с гарантией.",
    h1: "Ремонт стиральных машин в Москве",
    seoText: "На Нашло — актуальные объявления по ремонту стиральных машин в Москве. Выезд в день обращения.",
    categorySlug: "services",
    internalCategorySlug: "services",
    city: "Москва",
    fixedParams: { subcategory: "repair_home" },
    indexable: true,
    priority: 0.8,
    changefreq: "weekly",
  },
  {
    slug: "remont-kvartir-moskva",
    title: "Ремонт квартир в Москве",
    seoTitle: "Ремонт квартир в Москве — бригады и мастера | Нашло",
    seoDescription: "Объявления по ремонту квартир в Москве. Косметический, капитальный, под ключ. Цены и отзывы на Нашло.",
    h1: "Ремонт квартир в Москве",
    seoText: "Найдите бригаду или мастера для ремонта квартиры в Москве. Свежие объявления с ценами, фото и отзывами.",
    categorySlug: "services",
    internalCategorySlug: "services",
    city: "Москва",
    fixedParams: { subcategory: "repair_apartment" },
    indexable: true,
    priority: 0.85,
    changefreq: "daily",
  },
  {
    slug: "remont-kvartir-spb",
    title: "Ремонт квартир в Санкт-Петербурге",
    seoTitle: "Ремонт квартир в Санкт-Петербурге — под ключ | Нашло",
    seoDescription: "Бригады и мастера по ремонту квартир в Санкт-Петербурге. Косметический и капитальный ремонт.",
    h1: "Ремонт квартир в Санкт-Петербурге",
    seoText: "Объявления по ремонту квартир в Санкт-Петербурге на Нашло. Сравнивайте цены и условия.",
    categorySlug: "services",
    internalCategorySlug: "services",
    city: "Санкт-Петербург",
    fixedParams: { subcategory: "repair_apartment" },
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "remont-kvartir-krasnodar",
    title: "Ремонт квартир в Краснодаре",
    seoTitle: "Ремонт квартир в Краснодаре — мастера и бригады | Нашло",
    seoDescription: "Ремонт квартир в Краснодаре: косметический, капитальный, под ключ. Объявления с ценами.",
    h1: "Ремонт квартир в Краснодаре",
    seoText: "Найдите мастера по ремонту квартиры в Краснодаре. Свежие объявления на Нашло.",
    categorySlug: "services",
    internalCategorySlug: "services",
    city: "Краснодар",
    fixedParams: { subcategory: "repair_apartment" },
    indexable: true,
    priority: 0.75,
    changefreq: "weekly",
  },
  {
    slug: "gruzchiki-moskva",
    title: "Грузчики в Москве",
    seoTitle: "Грузчики в Москве — найти на Нашло",
    seoDescription: "Объявления грузчиков и грузоперевозчиков в Москве. Квартирные переезды, вывоз мебели, доставка.",
    h1: "Грузчики в Москве",
    seoText: "Найдите грузчиков в Москве на Нашло. Квартирные переезды, офисные переезды, вывоз мусора.",
    categorySlug: "services",
    internalCategorySlug: "services",
    city: "Москва",
    fixedParams: { subcategory: "moving" },
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "gruzchiki-spb",
    title: "Грузчики в Санкт-Петербурге",
    seoTitle: "Грузчики в Санкт-Петербурге — переезды | Нашло",
    seoDescription: "Грузчики в Санкт-Петербурге: переезды, вывоз мебели, доставка. Свежие объявления на Нашло.",
    h1: "Грузчики в Санкт-Петербурге",
    seoText: "Объявления грузчиков в Санкт-Петербурге. Квартирные и офисные переезды, разгрузка фур.",
    categorySlug: "services",
    internalCategorySlug: "services",
    city: "Санкт-Петербург",
    fixedParams: { subcategory: "moving" },
    indexable: true,
    priority: 0.75,
    changefreq: "daily",
  },
  {
    slug: "repetitor-angliyskiy-moskva",
    title: "Репетитор по английскому в Москве",
    seoTitle: "Репетитор по английскому языку в Москве | Нашло",
    seoDescription: "Найдите репетитора по английскому языку в Москве. Цены, отзывы и контакты на Нашло.",
    h1: "Репетитор по английскому в Москве",
    seoText: "Объявления репетиторов по английскому языку в Москве. Для детей и взрослых, онлайн и офлайн.",
    categorySlug: "services",
    internalCategorySlug: "services",
    city: "Москва",
    fixedParams: { subcategory: "education" },
    indexable: true,
    priority: 0.75,
    changefreq: "weekly",
  },

  // ─── НЕДВИЖИМОСТЬ × ГОРОДА ────────────────────────────────────────────────
  {
    slug: "snyat-kvartiru-moskva",
    title: "Снять квартиру в Москве",
    seoTitle: "Снять квартиру в Москве — аренда без посредников | Нашло",
    seoDescription: "Объявления аренды квартир в Москве. Без посредников, с фото, от частных лиц. Актуальные цены на Нашло.",
    h1: "Снять квартиру в Москве",
    seoText: "На Нашло — свежие объявления аренды квартир в Москве. Фильтры по районам, метро, цене и количеству комнат.",
    categorySlug: "real-estate",
    internalCategorySlug: "real-estate",
    city: "Москва",
    fixedParams: { deal: "rent", type: "apartment" },
    indexable: true,
    priority: 0.9,
    changefreq: "daily",
  },
  {
    slug: "snyat-kvartiru-spb",
    title: "Снять квартиру в Санкт-Петербурге",
    seoTitle: "Снять квартиру в Санкт-Петербурге — аренда | Нашло",
    seoDescription: "Аренда квартир в Санкт-Петербурге без посредников. Свежие объявления с фото и ценами.",
    h1: "Снять квартиру в Санкт-Петербурге",
    seoText: "Объявления аренды квартир в Санкт-Петербурге. Долгосрочная и посуточная аренда на Нашло.",
    categorySlug: "real-estate",
    internalCategorySlug: "real-estate",
    city: "Санкт-Петербург",
    fixedParams: { deal: "rent", type: "apartment" },
    indexable: true,
    priority: 0.85,
    changefreq: "daily",
  },
  {
    slug: "snyat-kvartiru-krasnodar",
    title: "Снять квартиру в Краснодаре",
    seoTitle: "Снять квартиру в Краснодаре — аренда жилья | Нашло",
    seoDescription: "Аренда квартир в Краснодаре. Без посредников, свежие объявления с фото и контактами.",
    h1: "Снять квартиру в Краснодаре",
    seoText: "Найдите квартиру в аренду в Краснодаре на Нашло. Объявления частных лиц и агентств.",
    categorySlug: "real-estate",
    internalCategorySlug: "real-estate",
    city: "Краснодар",
    fixedParams: { deal: "rent", type: "apartment" },
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "snyat-kvartiru-ekaterinburg",
    title: "Снять квартиру в Екатеринбурге",
    seoTitle: "Снять квартиру в Екатеринбурге — аренда | Нашло",
    seoDescription: "Аренда квартир в Екатеринбурге. Актуальные объявления с фото, ценами и контактами.",
    h1: "Снять квартиру в Екатеринбурге",
    seoText: "Свежие объявления аренды квартир в Екатеринбурге на Нашло.",
    categorySlug: "real-estate",
    internalCategorySlug: "real-estate",
    city: "Екатеринбург",
    fixedParams: { deal: "rent", type: "apartment" },
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "kupit-kvartiru-moskva",
    title: "Купить квартиру в Москве",
    seoTitle: "Купить квартиру в Москве — объявления продажи | Нашло",
    seoDescription: "Продажа квартир в Москве от частных лиц и застройщиков. Актуальные цены, фото, контакты.",
    h1: "Купить квартиру в Москве",
    seoText: "Объявления о продаже квартир в Москве. Новостройки и вторичка, все районы на Нашло.",
    categorySlug: "real-estate",
    internalCategorySlug: "real-estate",
    city: "Москва",
    fixedParams: { deal: "sell", type: "apartment" },
    indexable: true,
    priority: 0.9,
    changefreq: "daily",
  },
  {
    slug: "kupit-kvartiru-spb",
    title: "Купить квартиру в Санкт-Петербурге",
    seoTitle: "Купить квартиру в Санкт-Петербурге | Нашло",
    seoDescription: "Продажа квартир в Санкт-Петербурге. Вторичка и новостройки, все районы.",
    h1: "Купить квартиру в Санкт-Петербурге",
    seoText: "Свежие объявления о продаже квартир в Санкт-Петербурге на Нашло.",
    categorySlug: "real-estate",
    internalCategorySlug: "real-estate",
    city: "Санкт-Петербург",
    fixedParams: { deal: "sell", type: "apartment" },
    indexable: true,
    priority: 0.85,
    changefreq: "daily",
  },
  {
    slug: "kupit-kvartiru-krasnodar",
    title: "Купить квартиру в Краснодаре",
    seoTitle: "Купить квартиру в Краснодаре — продажа жилья | Нашло",
    seoDescription: "Продажа квартир в Краснодаре от собственников. Фото, цены, контакты на Нашло.",
    h1: "Купить квартиру в Краснодаре",
    seoText: "Объявления о продаже квартир в Краснодаре. Выбирайте по цене, площади и количеству комнат.",
    categorySlug: "real-estate",
    internalCategorySlug: "real-estate",
    city: "Краснодар",
    fixedParams: { deal: "sell", type: "apartment" },
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "sdat-kvartiru-moskva",
    title: "Сдать квартиру в Москве",
    seoTitle: "Сдать квартиру в Москве — разместить объявление | Нашло",
    seoDescription: "Разместите объявление о сдаче квартиры в Москве на Нашло. Бесплатно, быстро, без посредников.",
    h1: "Сдать квартиру в Москве",
    seoText: "Сдайте квартиру в Москве быстро через Нашло. Тысячи арендаторов ищут жильё прямо сейчас.",
    categorySlug: "real-estate",
    internalCategorySlug: "real-estate",
    city: "Москва",
    fixedParams: { deal: "rent", type: "apartment" },
    indexable: true,
    priority: 0.8,
    changefreq: "weekly",
  },

  // ─── АВТО × ГОРОДА ────────────────────────────────────────────────────────
  {
    slug: "kupit-avtomobil-moskva",
    title: "Купить автомобиль в Москве",
    seoTitle: "Купить автомобиль в Москве — объявления с пробегом | Нашло",
    seoDescription: "Продажа автомобилей в Москве от частных лиц и дилеров. Новые и б/у авто с фото.",
    h1: "Купить автомобиль в Москве",
    seoText: "Объявления о продаже автомобилей в Москве. Легковые, внедорожники, минивэны — все марки на Нашло.",
    categorySlug: "cars",
    internalCategorySlug: "cars",
    city: "Москва",
    indexable: true,
    priority: 0.9,
    changefreq: "daily",
  },
  {
    slug: "kupit-avtomobil-spb",
    title: "Купить автомобиль в Санкт-Петербурге",
    seoTitle: "Купить автомобиль в Санкт-Петербурге | Нашло",
    seoDescription: "Продажа авто в Санкт-Петербурге. Свежие объявления с фото, ценами и контактами продавцов.",
    h1: "Купить автомобиль в Санкт-Петербурге",
    seoText: "Найдите автомобиль в Санкт-Петербурге на Нашло. Широкий выбор марок и моделей.",
    categorySlug: "cars",
    internalCategorySlug: "cars",
    city: "Санкт-Петербург",
    indexable: true,
    priority: 0.85,
    changefreq: "daily",
  },
  {
    slug: "kupit-avtomobil-krasnodar",
    title: "Купить автомобиль в Краснодаре",
    seoTitle: "Купить автомобиль в Краснодаре — авто с пробегом | Нашло",
    seoDescription: "Продажа автомобилей в Краснодаре. Частные продавцы и дилеры. Актуальные цены.",
    h1: "Купить автомобиль в Краснодаре",
    seoText: "Объявления о продаже авто в Краснодаре. Все марки и модели, фото и история обслуживания.",
    categorySlug: "cars",
    internalCategorySlug: "cars",
    city: "Краснодар",
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "kupit-avtomobil-ekaterinburg",
    title: "Купить автомобиль в Екатеринбурге",
    seoTitle: "Купить автомобиль в Екатеринбурге | Нашло",
    seoDescription: "Авто с пробегом и новые машины в Екатеринбурге. Объявления от частников и дилеров.",
    h1: "Купить автомобиль в Екатеринбурге",
    seoText: "Свежие объявления о продаже автомобилей в Екатеринбурге на Нашло.",
    categorySlug: "cars",
    internalCategorySlug: "cars",
    city: "Екатеринбург",
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "prodat-avtomobil-moskva",
    title: "Продать автомобиль в Москве",
    seoTitle: "Продать автомобиль в Москве — разместить объявление | Нашло",
    seoDescription: "Разместите объявление о продаже авто в Москве бесплатно на Нашло. Быстро и без посредников.",
    h1: "Продать автомобиль в Москве",
    seoText: "Продайте свой автомобиль в Москве быстро. Разместите объявление на Нашло бесплатно.",
    categorySlug: "cars",
    internalCategorySlug: "cars",
    city: "Москва",
    indexable: true,
    priority: 0.8,
    changefreq: "weekly",
  },
  {
    slug: "kupit-mototsikl-moskva",
    title: "Купить мотоцикл в Москве",
    seoTitle: "Купить мотоцикл в Москве — объявления | Нашло",
    seoDescription: "Продажа мотоциклов в Москве. Новые и б/у, все марки — Honda, Yamaha, Kawasaki, BMW.",
    h1: "Купить мотоцикл в Москве",
    seoText: "Объявления о продаже мотоциклов в Москве. Спорт, туризм, классика, эндуро на Нашло.",
    categorySlug: "motorcycles",
    internalCategorySlug: "motorcycles",
    city: "Москва",
    indexable: true,
    priority: 0.75,
    changefreq: "weekly",
  },

  // ─── ЭЛЕКТРОНИКА × ГОРОДА ─────────────────────────────────────────────────
  {
    slug: "kupit-iphone-moskva",
    title: "Купить iPhone в Москве",
    seoTitle: "Купить iPhone в Москве — новый и б/у | Нашло",
    seoDescription: "Продажа iPhone в Москве. Новые, б/у, восстановленные — все модели. Актуальные цены.",
    h1: "Купить iPhone в Москве",
    seoText: "Объявления о продаже iPhone в Москве. iPhone 15, 14, 13, SE — фото и цены от частных продавцов.",
    categorySlug: "phones",
    internalCategorySlug: "phones",
    city: "Москва",
    fixedParams: { brand: "Apple" },
    indexable: true,
    priority: 0.85,
    changefreq: "daily",
  },
  {
    slug: "kupit-iphone-spb",
    title: "Купить iPhone в Санкт-Петербурге",
    seoTitle: "Купить iPhone в Санкт-Петербурге | Нашло",
    seoDescription: "Продажа iPhone в Санкт-Петербурге. Все модели, новые и б/у. Свежие объявления.",
    h1: "Купить iPhone в Санкт-Петербурге",
    seoText: "На Нашло — объявления о продаже iPhone в Санкт-Петербурге. Сравнивайте цены и состояние.",
    categorySlug: "phones",
    internalCategorySlug: "phones",
    city: "Санкт-Петербург",
    fixedParams: { brand: "Apple" },
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "kupit-noutbuk-moskva",
    title: "Купить ноутбук в Москве",
    seoTitle: "Купить ноутбук в Москве — новый и б/у | Нашло",
    seoDescription: "Продажа ноутбуков в Москве. Новые и б/у — Apple, Lenovo, ASUS, HP, Dell. Актуальные цены.",
    h1: "Купить ноутбук в Москве",
    seoText: "Объявления о продаже ноутбуков в Москве. Игровые, офисные, ультрабуки от частных продавцов.",
    categorySlug: "laptops",
    internalCategorySlug: "laptops",
    city: "Москва",
    indexable: true,
    priority: 0.85,
    changefreq: "daily",
  },
  {
    slug: "kupit-noutbuk-spb",
    title: "Купить ноутбук в Санкт-Петербурге",
    seoTitle: "Купить ноутбук в Санкт-Петербурге | Нашло",
    seoDescription: "Ноутбуки в Санкт-Петербурге — новые и б/у. Все марки, честные цены, фото.",
    h1: "Купить ноутбук в Санкт-Петербурге",
    seoText: "Свежие объявления о продаже ноутбуков в Санкт-Петербурге на Нашло.",
    categorySlug: "laptops",
    internalCategorySlug: "laptops",
    city: "Санкт-Петербург",
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "kupit-televizor-moskva",
    title: "Купить телевизор в Москве",
    seoTitle: "Купить телевизор в Москве — б/у и новый | Нашло",
    seoDescription: "Продажа телевизоров в Москве. Samsung, LG, Sony, Philips — все диагонали. Объявления на Нашло.",
    h1: "Купить телевизор в Москве",
    seoText: "Объявления о продаже телевизоров в Москве. Smart TV, OLED, 4K — фото и цены.",
    categorySlug: "electronics",
    internalCategorySlug: "electronics",
    city: "Москва",
    indexable: true,
    priority: 0.75,
    changefreq: "weekly",
  },
  {
    slug: "kupit-planshет-moskva",
    title: "Купить планшет в Москве",
    seoTitle: "Купить планшет в Москве — iPad и Android | Нашло",
    seoDescription: "Продажа планшетов в Москве. iPad, Samsung Galaxy Tab, Lenovo — новые и б/у.",
    h1: "Купить планшет в Москве",
    seoText: "Объявления о продаже планшетов в Москве. Выбирайте по бренду, диагонали и цене.",
    categorySlug: "phones",
    internalCategorySlug: "phones",
    city: "Москва",
    indexable: true,
    priority: 0.75,
    changefreq: "weekly",
  },

  // ─── ОДЕЖДА × ГОРОДА ──────────────────────────────────────────────────────
  {
    slug: "kupit-odezhdu-moskva",
    title: "Купить одежду в Москве",
    seoTitle: "Купить одежду в Москве б/у — секонд хенд | Нашло",
    seoDescription: "Продажа одежды в Москве от частных лиц. Б/у в хорошем состоянии, брендовая и повседневная.",
    h1: "Купить одежду в Москве",
    seoText: "Объявления о продаже одежды в Москве на Нашло. Мужская, женская, детская — отличные цены.",
    categorySlug: "clothing",
    internalCategorySlug: "clothing",
    city: "Москва",
    indexable: true,
    priority: 0.75,
    changefreq: "daily",
  },
  {
    slug: "kupit-odezhdu-spb",
    title: "Купить одежду в Санкт-Петербурге",
    seoTitle: "Одежда б/у в Санкт-Петербурге — объявления | Нашло",
    seoDescription: "Продажа одежды в Санкт-Петербурге. Б/у, брендовая, для всей семьи. Свежие объявления.",
    h1: "Купить одежду в Санкт-Петербурге",
    seoText: "Свежие объявления о продаже одежды в Санкт-Петербурге на Нашло.",
    categorySlug: "clothing",
    internalCategorySlug: "clothing",
    city: "Санкт-Петербург",
    indexable: true,
    priority: 0.7,
    changefreq: "daily",
  },

  // ─── РАБОТА × ГОРОДА ──────────────────────────────────────────────────────
  {
    slug: "rabota-voditel-moskva",
    title: "Работа водителем в Москве",
    seoTitle: "Работа водителем в Москве — вакансии | Нашло",
    seoDescription: "Вакансии водителя в Москве. Такси, грузоперевозки, курьер, личный водитель. Свежие объявления.",
    h1: "Работа водителем в Москве",
    seoText: "Найдите работу водителем в Москве на Нашло. Вакансии от работодателей с зарплатой и условиями.",
    categorySlug: "jobs",
    internalCategorySlug: "jobs",
    city: "Москва",
    fixedParams: { jobCategory: "driver" },
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "rabota-prodavets-moskva",
    title: "Работа продавцом в Москве",
    seoTitle: "Работа продавцом в Москве — вакансии | Нашло",
    seoDescription: "Вакансии продавца в Москве. В магазинах, торговых центрах, онлайн. Актуальные объявления.",
    h1: "Работа продавцом в Москве",
    seoText: "Ищете работу продавцом в Москве? На Нашло — актуальные вакансии от работодателей.",
    categorySlug: "jobs",
    internalCategorySlug: "jobs",
    city: "Москва",
    fixedParams: { jobCategory: "sales" },
    indexable: true,
    priority: 0.75,
    changefreq: "daily",
  },
  {
    slug: "rabota-kurier-moskva",
    title: "Работа курьером в Москве",
    seoTitle: "Работа курьером в Москве — вакансии на Нашло",
    seoDescription: "Вакансии курьера в Москве. Пеший, авто, велокурьер. Свежие объявления от работодателей.",
    h1: "Работа курьером в Москве",
    seoText: "Объявления о работе курьером в Москве на Нашло. Полный день, частичная занятость, подработка.",
    categorySlug: "jobs",
    internalCategorySlug: "jobs",
    city: "Москва",
    fixedParams: { jobCategory: "delivery" },
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "rabota-stroitel-moskva",
    title: "Работа строителем в Москве",
    seoTitle: "Работа строителем в Москве — вакансии | Нашло",
    seoDescription: "Вакансии строителей в Москве. Отделочник, каменщик, сварщик, разнорабочий. Актуальные предложения.",
    h1: "Работа строителем в Москве",
    seoText: "Найдите работу в строительстве в Москве на Нашло. Вахта, полный день, бригады.",
    categorySlug: "jobs",
    internalCategorySlug: "jobs",
    city: "Москва",
    fixedParams: { jobCategory: "construction" },
    indexable: true,
    priority: 0.75,
    changefreq: "daily",
  },

  // ─── ЖИВОТНЫЕ × ГОРОДА ────────────────────────────────────────────────────
  {
    slug: "kupit-sobaku-moskva",
    title: "Купить собаку в Москве",
    seoTitle: "Купить собаку в Москве — щенки и взрослые | Нашло",
    seoDescription: "Продажа собак в Москве. Щенки с документами и без, взрослые собаки в добрые руки.",
    h1: "Купить собаку в Москве",
    seoText: "Объявления о продаже собак в Москве на Нашло. Породистые и беспородные, щенки и взрослые.",
    categorySlug: "animals",
    internalCategorySlug: "animals",
    city: "Москва",
    fixedParams: { animalType: "dogs" },
    indexable: true,
    priority: 0.75,
    changefreq: "daily",
  },
  {
    slug: "kupit-koshku-moskva",
    title: "Купить кошку в Москве",
    seoTitle: "Купить кошку в Москве — котята и взрослые | Нашло",
    seoDescription: "Продажа кошек в Москве. Котята с документами, породистые и беспородные.",
    h1: "Купить кошку в Москве",
    seoText: "Объявления о продаже кошек в Москве. Котята мейн-кун, британцы, шотландцы и другие породы.",
    categorySlug: "animals",
    internalCategorySlug: "animals",
    city: "Москва",
    fixedParams: { animalType: "cats" },
    indexable: true,
    priority: 0.75,
    changefreq: "daily",
  },
  {
    slug: "otdat-koshku-darom-moskva",
    title: "Отдать кошку даром в Москве",
    seoTitle: "Отдать кошку даром в Москве — в добрые руки | Нашло",
    seoDescription: "Кошки в добрые руки в Москве. Бесплатные объявления от владельцев.",
    h1: "Отдать кошку даром в Москве",
    seoText: "На Нашло — объявления «отдам кошку даром» в Москве. Кошки и котята ищут заботливых хозяев.",
    categorySlug: "animals",
    internalCategorySlug: "animals",
    city: "Москва",
    fixedParams: { animalType: "cats", price: "free" },
    indexable: true,
    priority: 0.7,
    changefreq: "daily",
  },

  // ─── ДЛЯ ДОМА × ГОРОДА ────────────────────────────────────────────────────
  {
    slug: "kupit-mebel-moskva",
    title: "Купить мебель в Москве",
    seoTitle: "Купить мебель в Москве — б/у и новая | Нашло",
    seoDescription: "Продажа мебели в Москве от частных лиц. Диваны, шкафы, кровати, столы — все объявления на Нашло.",
    h1: "Купить мебель в Москве",
    seoText: "Объявления о продаже мебели в Москве. Б/у в хорошем состоянии и новая мебель.",
    categorySlug: "home",
    internalCategorySlug: "home",
    city: "Москва",
    fixedParams: { subcategory: "furniture" },
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "kupit-mebel-spb",
    title: "Купить мебель в Санкт-Петербурге",
    seoTitle: "Купить мебель в Санкт-Петербурге | Нашло",
    seoDescription: "Продажа мебели в Санкт-Петербурге. Диваны, шкафы, комоды — свежие объявления.",
    h1: "Купить мебель в Санкт-Петербурге",
    seoText: "Свежие объявления о продаже мебели в Санкт-Петербурге на Нашло.",
    categorySlug: "home",
    internalCategorySlug: "home",
    city: "Санкт-Петербург",
    fixedParams: { subcategory: "furniture" },
    indexable: true,
    priority: 0.75,
    changefreq: "daily",
  },
  {
    slug: "kupit-holodilnik-moskva",
    title: "Купить холодильник в Москве",
    seoTitle: "Купить холодильник в Москве — б/у | Нашло",
    seoDescription: "Продажа холодильников в Москве. Б/у и новые — Samsung, LG, Bosch. Объявления с фото.",
    h1: "Купить холодильник в Москве",
    seoText: "Объявления о продаже холодильников в Москве. Однокамерные, двухкамерные, side-by-side.",
    categorySlug: "home",
    internalCategorySlug: "home",
    city: "Москва",
    fixedParams: { subcategory: "appliances" },
    indexable: true,
    priority: 0.75,
    changefreq: "weekly",
  },

  // ─── ДЕТСКИЕ ТОВАРЫ × ГОРОДА ──────────────────────────────────────────────
  {
    slug: "kupit-detskuyu-kolyasku-moskva",
    title: "Купить детскую коляску в Москве",
    seoTitle: "Детские коляски в Москве — б/у | Нашло",
    seoDescription: "Продажа детских колясок в Москве. Б/у, новые — трансформеры, прогулочные, всесезонные.",
    h1: "Купить детскую коляску в Москве",
    seoText: "Объявления о продаже детских колясок в Москве. Выбирайте по типу, возрасту и цене.",
    categorySlug: "kids",
    internalCategorySlug: "kids",
    city: "Москва",
    fixedParams: { subcategory: "strollers" },
    indexable: true,
    priority: 0.75,
    changefreq: "daily",
  },
  {
    slug: "kupit-detskie-igrushki-moskva",
    title: "Купить детские игрушки в Москве",
    seoTitle: "Детские игрушки в Москве б/у | Нашло",
    seoDescription: "Продажа детских игрушек в Москве от частных лиц. Б/у, новые, LEGO, куклы, машинки.",
    h1: "Купить детские игрушки в Москве",
    seoText: "Объявления о продаже детских игрушек в Москве. Отличные цены от частных продавцов.",
    categorySlug: "kids",
    internalCategorySlug: "kids",
    city: "Москва",
    fixedParams: { subcategory: "toys" },
    indexable: true,
    priority: 0.7,
    changefreq: "daily",
  },

  // ─── СПОРТ × ГОРОДА ───────────────────────────────────────────────────────
  {
    slug: "kupit-велосипед-moskva",
    title: "Купить велосипед в Москве",
    seoTitle: "Купить велосипед в Москве — б/у и новый | Нашло",
    seoDescription: "Продажа велосипедов в Москве. Горные, дорожные, городские — б/у и новые. Свежие объявления.",
    h1: "Купить велосипед в Москве",
    seoText: "Объявления о продаже велосипедов в Москве. Взрослые, детские, электровелосипеды.",
    categorySlug: "sport",
    internalCategorySlug: "sport",
    city: "Москва",
    fixedParams: { subcategory: "bikes" },
    indexable: true,
    priority: 0.75,
    changefreq: "weekly",
  },
  {
    slug: "kupit-trenazher-moskva",
    title: "Купить тренажёр в Москве",
    seoTitle: "Тренажёры в Москве б/у — купить | Нашло",
    seoDescription: "Продажа тренажёров в Москве. Б/у и новые: беговые дорожки, велотренажёры, силовые.",
    h1: "Купить тренажёр в Москве",
    seoText: "Объявления о продаже тренажёров в Москве. Домашние тренажёры по выгодным ценам.",
    categorySlug: "sport",
    internalCategorySlug: "sport",
    city: "Москва",
    fixedParams: { subcategory: "fitness" },
    indexable: true,
    priority: 0.7,
    changefreq: "weekly",
  },

  // ─── БЕСПЛАТНОЕ × ГОРОДА ──────────────────────────────────────────────────
  {
    slug: "besplatnye-veshchi-moskva",
    title: "Бесплатные вещи в Москве",
    seoTitle: "Бесплатные вещи в Москве — отдам даром | Нашло",
    seoDescription: "Объявления «отдам даром» в Москве. Мебель, одежда, техника — бесплатно для вас.",
    h1: "Бесплатные вещи в Москве",
    seoText: "На Нашло — объявления о бесплатных вещах в Москве. Мебель, одежда, техника и многое другое.",
    categorySlug: "goods",
    internalCategorySlug: "goods",
    city: "Москва",
    fixedParams: { price: "free" },
    indexable: true,
    priority: 0.7,
    changefreq: "daily",
  },

  // ─── ЗАПЧАСТИ × ГОРОДА ────────────────────────────────────────────────────
  {
    slug: "zapchasti-avto-moskva",
    title: "Запчасти для автомобилей в Москве",
    seoTitle: "Запчасти для авто в Москве — б/у | Нашло",
    seoDescription: "Продажа автозапчастей в Москве. Б/у и новые — двигатели, КПП, кузовные детали.",
    h1: "Запчасти для автомобилей в Москве",
    seoText: "Объявления о продаже автозапчастей в Москве. Все марки и модели. Свежие объявления на Нашло.",
    categorySlug: "parts",
    internalCategorySlug: "parts",
    city: "Москва",
    indexable: true,
    priority: 0.8,
    changefreq: "daily",
  },
  {
    slug: "zapchasti-avto-spb",
    title: "Запчасти для автомобилей в Санкт-Петербурге",
    seoTitle: "Автозапчасти в Санкт-Петербурге | Нашло",
    seoDescription: "Продажа автозапчастей в Санкт-Петербурге. Б/у и новые детали для всех марок авто.",
    h1: "Запчасти для автомобилей в Санкт-Петербурге",
    seoText: "Свежие объявления о продаже автозапчастей в Санкт-Петербурге на Нашло.",
    categorySlug: "parts",
    internalCategorySlug: "parts",
    city: "Санкт-Петербург",
    indexable: true,
    priority: 0.75,
    changefreq: "daily",
  },
]

/** Lookup order: 1. static array  2. programmatic engine */
export function getSeoLandingBySlug(slug: string) {
  const fromStatic = SEO_LANDING_PAGES.find((p) => p.slug === slug)
  if (fromStatic) return fromStatic
  // Lazy import to keep this file free of heavy deps at module level.
  // In Next.js this is fine since it runs server-side only.
  try {
    const { getProgrammaticLanding } = require("./programmatic")
    return getProgrammaticLanding(slug) ?? null
  } catch {
    return null
  }
}

export function getIndexableSeoLandings() {
  return SEO_LANDING_PAGES.filter((p) => p.indexable)
}
