-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WANT_TO_BUY_NEW_OFFER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WANT_TO_BUY_OFFER_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WANT_TO_BUY_OFFER_DECLINED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WANT_TO_BUY_EXPIRING_SOON';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WANT_TO_BUY_REJECTED';
