-- AlterTable
ALTER TABLE "BannerSlotAd" ADD COLUMN IF NOT EXISTS "mediaType" "AdMediaType" NOT NULL DEFAULT 'IMAGE';
ALTER TABLE "BannerSlotAd" ADD COLUMN IF NOT EXISTS "mediaMimeType" TEXT;
ALTER TABLE "BannerSlotAd" ADD COLUMN IF NOT EXISTS "mediaWidth" INTEGER;
ALTER TABLE "BannerSlotAd" ADD COLUMN IF NOT EXISTS "mediaHeight" INTEGER;
ALTER TABLE "BannerSlotAd" ADD COLUMN IF NOT EXISTS "mediaDuration" INTEGER;
